### PR TITLE
Fix item with subitems crash when clicked

### LINKED ISSUE #81: Clicking on item with subitems causes type error
Clicking on a menu item that has subitems (where the desired behavior is to have no action) causes the error:

 props.data.handler is not a function

This error can be reproduced by clicking on the "extra" menu item found at the example [here](https://retejs.org/examples/context-menu). 

I imagine the solution is to add a empty function like:
`handler() {}`

on [this](https://github.com/retejs/context-menu-plugin/blob/35831a081dfa64c4539406c8e93b12194eb66698/src/presets/classic/factory.ts#L32) line. I [forked](https://github.com/Claybarn/context-menu-plugin) this repo in the hopes of making a PR with this change, however I can't ensure it fixes the problem because the rete-cli emits a "Type generating failed" error when attempting to compile the context-menu-plugin.

### PR DESCRIPTION
**Pull request by Claybarn**
Add dummy handler to item with subitems to prevent crashing. Fixes #81.

### CODE REVIEW

**Comment by Claybarn** [comment]
This solved the crashing issue but introduced a new one. It prevented zooming in and out on the graph. Will see if there is another solution.

**Comment by Claybarn** [comment]
Actually I take that back, the zooming issue happens if I compile the module from scratch without any changes at all.

File: src/presets/classic/factory.ts [hunk 1]
```diff
@@ -28,6 +28,7 @@ export function createItem<S extends BSchemes>(
   }
   return <Item>{
     ...item,
-    subitems: factory.map((data, i) => createItem(data, i, context))
+    subitems: factory.map((data, i) => createItem(data, i, context)),
+    handler: Function()
```
Comment (Ni55aN) [inline src/presets/classic/factory.ts]: this is unsafe due to Content Security Policy directive: "script-src"

**Review by Ni55aN — CHANGES_REQUESTED** [review]

**Comment by Ni55aN** [comment]
>  the zooming issue happens if I compile the module from scratch

https://github.com/retejs/react-plugin/blob/main/src/presets/context-menu/components/Menu.tsx#L39

this is expected behavior. Do you think it should passthrough context menu?

File: src/presets/classic/factory.ts (hunk 1 above)
Comment (Ni55aN) [reply src/presets/classic/factory.ts]: also, can you squash commits into a single one with name of the format "fix: <your message>"? (unfortunately this part is not covered in the Contribution guide)

**Comment by Claybarn** [comment]
I collapsed the commits, let me know if anything else needs changing.

**Comment by Ni55aN** [comment]
please check CI and Commit linter workflows

**Comment by Ni55aN** [comment]
commit message isn't conventional

**Comment by Ni55aN** [comment]
anyway, I can merge it into different branch and rebase

**Review by Ni55aN — APPROVED** [review]
